############################# English ############################
[en]
languageName = "En"
title = "Halara Network"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Server"
footer_menu_middle = "Archive"
footer_menu_right = "Support"
footer_content = "Built around community, passionate about innovation."
# copyright
copyright = "© 2021 [Cooper Sullivan](https://coopersully.me)"
